### ISSUE TITLE
Improve missing events detection

### ISSUE THREAD

**Issue by dlapin-cribl** [smilinazzo/timberbrook#9]
https://github.com/smilinazzo/timberbrook/blob/master/src/tools/utils.py#L47
this check will stop the test run on first missing event

**Comment by smilinazzo** [comment]
yes, that was intentional. It did come down to a decision about how much info I wanted to include in the failure scenario. ALL failures? Or just the first. I had decided that the run would still fail if it 'almost passed' because a single event was missing or 'catastrophically failed' because every event was different. And then give what information I had that caused the failure (dup/missing). 

Normally, I would have spoken with the developers to see what information they would require if this particular test failed. So, that  we had at least something to go on for debug when it did.
